name: Deriv App ID Generator

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  pull-requests: write
  statuses: write

on:
    issue_comment:
        types: [edited]

jobs:
    generate_app_id:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - name: Capture Vercel preview URL
              id: vercel_preview_url
              run: |
                pull_request="https://lol.deriv-com-playground.pages.dev/"
                echo "vercel_preview_url=$pull_request" > $GITHUB_OUTPUT
                  
            - name: Generate Deriv App ID for deployment Preview URL
              id: generate_app_id
              run: |
                pr_url="https://github.com/adrienne-deriv/deriv-app-playground/pull/15"
                echo "app_id=123" > $GITHUB_OUTPUT
                echo "pr_url=$pr_url" > $GITHUB_OUTPUT
                
                      
            - name: Notify translations team
              if: github.ref_name == 'deriv_app_translations_2'
              run: |
                content="Paimon has retrieved the generated test link for the updated translations:\n"
                content+=":paperclip: *Pull Request*: ${{ steps.generate_app_id.outputs.pr_url }}\n"
                content+=":link: *Test Link*: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}\n"
                content+=":id: *App ID*: ${{ steps.generate_app_id.outputs.app_id }}"

                if [ -n "${{ secrets.SLACK_TRANSLATIONS_TEAM_WEBHOOK }}" ]; then
                  curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"$content\" }" ${{ secrets.SLACK_TRANSLATIONS_TEAM_WEBHOOK }}
                fi
