name: Deriv App ID Generator

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  pull-requests: write
  statuses: write

on:
    issue_comment:
        types: [edited]

jobs:
    generate_app_id:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - name: Capture Vercel preview URL
              id: vercel_preview_url
              run: |
                pull_request="https://lol.deriv-com-playground.pages.dev/"
                echo "${{ github.ref_name }}"
                echo "${{ github.ref }}"
                echo "$GITHUB_REF_NAME"
                echo "vercel_preview_url=$pull_request" > $GITHUB_OUTPUT
                  
            - name: Generate Deriv App ID for deployment Preview URL
              id: generate_app_id
              run: |
                pr_url="https://github.com/adrienne-deriv/deriv-app-playground/pull/17"
                app_id="123"
                echo "pr_url=$pr_url" > $GITHUB_OUTPUT
                
            - name: Get pull request
              id: get-pr
              uses: octokit/request-action@v2.x
              with:
                route: GET ${{ github.event.issue.pull_request.url }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
            - name: Get user
              id: get-user
              uses: octokit/request-action@v2.x
              with:
                route: GET ${{ steps.get-pr.outputs.data.user.url }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
            - name: Find Slack user
              id: find-slack-user
              uses: scribd/find-slack-user-action@v1
              with:
                slack-token: ${{ secrets.SLACK_API_TOKEN }}
                email: ${{ steps.get-user.outputs.data.email }}

            - name: Post to a Slack channel
              uses: slackapi/slack-github-action@v1.24.0
              with:
                channel-id: ${{ steps.find-slack-user.outputs.member-id }}
                slack-message: |
                    Paimon has retrieved the test link for your recent pull request:
                    - *PR*: ${{ steps.generate_app_id.outputs.pr_url }}
                    - *URLs*:
                        - *w/ App ID + Server*: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}?qa_server=red.binaryws.com&app_id=${{ steps.generate_app_id.outputs.app_id }}
                        - *Original*: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
                    - *App ID*: ${{ steps.generate_app_id.outputs.app_id }}
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
                
  
            - name: Retrieve pull request head branch
              uses: xt0rted/pull-request-comment-branch@v2
              id: comment-branch
                      
            - name: Notify translations team
              if: ${{ steps.comment-branch.outputs.head_ref == 'test_deriv_app_translations_2' }}
              run: |
                content="Paimon has retrieved the generated test link for the updated translations:\n"
                content+=":paperclip: *Pull Request*: ${{ steps.generate_app_id.outputs.pr_url }}\n"
                content+=":link: *Test Link*: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}\n"
                content+=":id: *App ID*: 123"

                if [ -n "${{ secrets.SLACK_TRANSLATIONS_TEAM_WEBHOOK }}" ]; then
                  curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"$content\" }" ${{ secrets.SLACK_TRANSLATIONS_TEAM_WEBHOOK }}
                fi
