name: Notify translations team in Slack

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  pull-requests: write
  statuses: write

on:
    issue_comment:
        types: [edited]

jobs:
    test:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
        - name: Print
          run: |
            echo "${{ github.event.issue.pull_request.url }}"
            echo "${{ github.event.issue.pull_request.title }}"
            echo "${{ github.event.issue.pull_request.head_ref }}"
            echo "${{ github.ref_name }}"
            echo "${{ github.head_ref}}"
            echo "${{ github.ref }}"
    generate_app_id:
        if: ${{ github.event.issue.pull_request && github.ref_name == 'deriv_app_translations' }}
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
          - name: Capture test link URL
            id: test_link_url
            uses: binary-com/vercel-preview-url-action@v1.0.5
            with:
                GITHUB_TOKEN: ${{ github.token }}
                preview_url_regexp: \[Visit Preview\]\((.*?.pages.dev)\)

          - name: Send Slack message to translations team
            run: |
              if [ -n "${{ secrets.SLACK_TRANSLATIONS_TEAM_WEBHOOK }}" ]; then
                  echo "Sending message to Slack (#team_translations)"

                  project="${{ github.event.client_payload.project.name }}"
                  pull_request="https://github.com/${{ github.repository }}/pull/${{ github.event.issue.pull_request.number }}"
                  updated_language="${{ github.event.client_payload.targetLanguage.name }}"

                  content="Paimon noticed that there was an update in Crowdin for a language, here are the details of the changes:\n"
                  content+="**Project**: $project\n"
                  content+="**Pull Request**: $pull_request\n"
                  if [ -n "${{ steps.test_link_url.outputs.vercel_preview_url }}" ]; then
                    content+="**Test Link**: ${{ steps.test_link_url.outputs.vercel_preview_url }}\n"
                  fi
                  content+="**Updated language**: $updated_language\n"
                  curl -X POST -H 'Content-type: application/json' --data '{"text": $content }' ${{ secrets.SLACK_TRANSLATIONS_TEAM_WEBHOOK }}
              fi
