name: 'Update translations from Crowdin'

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - file-fully-reviewed

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Checkout to translations package
        run: |
            cd $(git rev-parse --show-toplevel)/packages/translations

      - name: Download translations 
        id: download_translations
        uses: crowdin/github-action@v1.11.0
        with:
          download_translations: true
          upload_sources: false
          push_sources: false
          push_translations: false
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Log translations
        run: |
          echo "${{ github.event.client_payload.file }}"

      
